---
title: "Project Work"
---

## PFE/Applied Learning

- This class counts as *Applied Learning*
- If you haven't submitted a link to your individual project repo, please do so ASAP:
    + Right now: Add you Github username to the spreadsheet in the **Dashboard- General** channel on Teams
    + Later: Submit a link to your individual project assignment on Teams

## Rest of the term
::: incremental
- Project work & Presentations
    + Individual presentations (M-TH, next week, about 5 per day)
        + Sign-up for a presentation slow on Teams
- Classtime will be used for project work
:::

## Mindset Until End of Semester

- You are an employee for a Data Science Company
- You have two projects: your individual and your group project
- It is up to you to manage your time:
    + Work on your individual project when you have down time from your group project
- Your Sentinel is your boss
- Reagan/Keion are your bosses boss

## Expectations

- Group Project:
    - You complete the tasks assigned to you by your manager in a timely fashion
    - You communicate with your manager and team members if you are having trouble completing your tasks on time
    - Carefully document all meetings so tasks can be tracked
- Individual Project:
    - You spend a minimum of 10 hours working on this project
    - If you finish in under 10 hours... you didn't pick a project that was hard enough, so do more
    - Be regularly committing your work so I can see your progress

## Evaluation

- Group Project (due end of term):
    + Self reflection/evaluation
    + Manager evaluations
- Individual Project(due end of term):
    + Self reflection/evaluation
    + Public defense/presentation

## Group Project: How you can fail

- Not completing your assigned tasks on time
    + If you are not making a good faith effort to complete your assigned tasks, your manager will notify me and I will step in. You will receive one warning
    + If you are unable to complete your tasks you MUST ask for help early. Waiting until the last minute to ask for help will be viewed as not completing your tasks on time
- If someone else has to complete your work for you

## Individual Project: How you can fail

- You fail to complete your work by the deadline
- You demonstrate a complete lack of understanding of your project during your defense
    + You cannot explain what you did and why you did it
    + You cannot answer basic follow-up questions about your project
    + You cannot explain what you learned

## Goal for Today: Brainstorm and Proposal {.smaller}

- Explore data for group project
- Each Feature Team should find a breakout room:
    - Add your location in the Dashboard - General channel on Teams
    - Sentinel: Create and/or checkout feature branch on GitHub for your team and push it to GitHub
    - Everyone else: Clone repo, checkout feature branch, create your own branch off of the feature branch
    - Start exploring and brainstorming (conduct your work in the `scartch` folder)
    - Deliverable for Wednesday morning: Quarto presentation  in `docs` on a proposal for visualizing your feature (Narrator Should Generate This for Sentinnel)
    - Once complete: Create a pull request to merge your work back to the feature branch
